config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'prototypes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "prototypes#index"
  resources :prototypes, only: [:index, :new, :create, :show, :edit, :update, :destroy  ] do
    resources :comments, only: :create
  end
  resources :users, only: :show
  # ネスト内に入れない。入れるとprototypeがないとuserが作れないとなってしまう。
  # ユーザーは第三者の為、何もなくても作成できる。
  # rails routesでIDは特定のものを指定する際にある。指定がない例えばindexやcreateにはIDはない。
end

# deviceは新規登録、削除、ログイン機能しかない。
# 更新や編集、新規投稿の機能はない為、自分で実装する必要がある。
# モデルを作成する。
# モデル別に必要なアクションを設定する。newは新規投稿。
# ↓は説明だけ。
# resources :rooms, only: [:new, :create] do
#   resources :messages, only: [:index, :create]
# end
# do はネスタ。
# roomの中のメッセージという意味にする。
# メッセージはルームに入ってからでないと打てない。
# doの下は前半少し空ける。
# 上記の関係になると、URLも/rooms/:room_id/messages になり、roomの中のとmesssageとなる。
# 本来は/rooms/:room_id/はない。
# サイドバーのチャットルーム名に、 <%= link_to room.name, room_messages_path(room) %>とリンクを設定します。

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :prototype
	validates :content, presence: true
end

app/models/prototype.rb
class Prototype < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent:  :destroy
	has_one_attached :image

	validates :title, presence: true
	validates :catch_copy, presence: true
	validates :concept, presence: true
	validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :prototypes
         has_many :comments
         validates :name, presence: true
         validates :profile, presence: true
         validates :occupation, presence: true
         validates :position, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :occupation, :position])
  end
end


# ActionController::Base は親モデル。<は親を継承する。
# ApplicationControllerはすべてのコントローラーに内容を発動する。
# 全てのコントローラーに発動したくない場合は、コントローラー別に記載する。
# if: :devise_controller?デバイスコントローラーが発動する前に[:name, :profile, :occupation, :position])新規登録は出来るようにする。

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@prototype = Prototype.find(params[:prototype_id])
		# @room = Room.find(params[:room_id]) prototype idからデータを見つける。
		@comment = Comment.new(comment_params)
		@comments = @prototype.comments
    # コメントを保存するだけの為、上記と書き方が違う。
    if @comment.save
  redirect_to "/prototypes/#{@comment.prototype.id}"
else
  render :"prototypes/show", status: :unprocessable_entity
end
# commentsコントローラーだが、prototypesコントローラーのshowに行きたい際は、別ディレクトリの為"prototypes/show"と記載する。
# @prototype = Prototype.find(params[:prototype_id]) →DBevweのprorotypeモデルのIDを一つ抜く。
# @comment = Comment.new(comment_params)保存をしようとしたコメントをインスタンス変数として空箱を作り、@commentに入れた。comment_paramsがある為、user_idのcurrent_user.idと、prototype_idのparams[:prototype_id])も一緒に保存。params[:prototype_id]は上記の3行目の情報。Dvevweのcommentsモデルにもコメントと一緒に保存されている。
# 今回は保存しようとした情報をif～定義したい為、@commentは必要。
# @commentsはvieで定義する為に必要。他の人のコメントも合わして一覧で表示させる為。





	end
		private
		def comment_params
			params.require(:comment).permit(:content).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
		end
		# biinding pry はエラーであろう場所のアクションの前に記述。
		# 今回はコメントを保存→保存されない為、createの後ろに記述。createに問題なければ、ターミナルは長文で続く。
		# 止まれば、create後に問題がある。
		# 1にはparamsを入れる。小さい波かっこの前にモデル名、波かっこの中にキーがある。
		# *キーはviewのフォーム箇所。入力欄。 <%= f.text_field :content,今回でいうと、contentがキー。
		# ストロングパラメーター（comment_params)の中身にcontentがあるか確認する。params.require がストロングパラメーター
		# permittの中身がcontentでなかった為、エラー。
		# params.require(:comment).permit(:content)→params.requireは指定するモデル。
		# permitはキー。vieのフォームを見る。

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  # showとindexアクションをする前にログインしていなかったら、ログイン画面に戻る。
  before_action :move_to_index, only: [:edit ]
  # editアクションをする前だけ～。
  # showとindex以外はログインしないと処理出来ない。before_action :authenticate_user!だけだとログインページに戻る。
  def index
    @prototypes = Prototype.all
    # @prototypesは自分で作成OKだが分かりやすい用語。Prototype.allはモデルのPrototypeの情報を全て
    # @users = User.all
  end



  def new
  @prototype = Prototype.new
end

def create
@prototype = Prototype.new(prototype_params)
    if @prototype.save
  redirect_to '/'
else
  render :new, status: :unprocessable_entity
end
end

def show
  @prototype = Prototype.find(params[:id])
  @comment = Comment.new
  @comments = @prototype.comments.includes(:user)
  # 一つの投稿（@prototype）に全てのコメント（ユーザー情報）も @commentsに代入。includesでN+1問題クリア。
end
# createメソッドは登録、保存後でもredirect_toを実行してしまう。問題なくても。
# その為、saveメソッドはif条件分岐が出来る。
# createメソッドはパラムスを使う必要がある。
# status: :unprocessable_entit セットでエラー表示されても入力した情報は保存されるという意味。

def edit
  @prototype = Prototype.find(params[:id])
end

def update
   @prototype = Prototype.find(params[:id])
   if @prototype.update(prototype_params)
    redirect_to prototype_path
  else
    render :edit, status: :unprocessable_entity
  end
end
# @prototypeは登録出来た場合は使用無。renderになった際だけ使用。
# prototype_pathでrails routesで確認すると、show以外にも、prototypeはあるが、GETが選定される。
# GET以外に飛びたい場合は、後ろにID_pathを入れる必要がある為、showに飛ぶ。
# その後、prorotype contorollerに飛び、vieのshowに飛ぶがその際は、controllerの@prototyoeをviwで使う。
# renderの場合は、そのままeditに飛んで、その際だけ、updateで定義した@prototypeを使う為、失敗後も保存はされる。

def destroy
  prototype = Prototype.find(params[:id])
  prototype.destroy
  redirect_to root_path
end

private
def prototype_params
  params.require(:prototype).permit(:title, :catch_copy, :concept, :image).merge(user_id: current_user.id)
end

def move_to_index
  resource = Prototype.find(params[:id])
  # unless user_signed_in?
    unless resource.user_id == current_user.id
      # unless prototype.user.name_signed_in?
      # unless current.user_signed_in?
      # require_owner
    redirect_to action: :index
  end
end
end

# 2行目のbefore_action :move_to_index, only: [:edit ]のmove_to_index(これは何でもよりメソッド)
# resourceも何でもよいメソッド。
# ユーザーIDとログインしている人が同じでなかった場合は、トップページに戻る。

# githubはまずはメイン状態で右のボタンを教えてから、コメント実装など作成する。
# 万が一、コメント実装などを作成してからの場合は、Default branchをmainに変える。（General)
# エラーが出た際は先にVCで修正してから、githubでrepoする。

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
    @prototypes = @user.prototypes
		# クリックされたUserモデルのデータを全て@userに入れる。
		# @をつけることにより、viewでも使える。@がないとローカル変数となり、ここでしか使えない。
		# @userを使うことにより、@user.nameでクリックしたユーザーの名前を表示する。
		# @user.profileであれば、プロフィールを表示する。
		# @prototypes = @user.prototypesは、viewで使用する場合、@prototypesで明示した方が短いので、これは記載した方がよい。
		# その為、カリキュラムの下記はなくても良い。
		# @nickname = user.nickname
    # @tweets = user.tweets
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Protospace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <%# ログインしているときは以下を表示するようにしましょう %>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, class: :nav__logout, data: { turbo_method: :delete } %>
              <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
            </div>
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <% else %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%= form_with model: prototype, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="card">
  <%= link_to image_tag(prototype.image, class: :card__img ), prototype_path(prototype.id)%>
  <%# prototype_pathはshow(詳細）アクションへ %>
  <%# ""は文字列として認識される為、削除。また、imageを表現する際はモデルのacticve～は不要 %>
  <div class="card__body">
    <%= link_to prototype.title, prototype_path(prototype.id), class: :card__title%>
    <p class="card__summary">
      <%= prototype.catch_copy %>
    </p>
    <%= link_to prototype.user.name, user_path(prototype.user.id), class: :card__user %>
    <%# prototype.user.jp はログインしていな時でも表示させる為に。current.userにすると、ログインしていない時は
    トップページが開かなくなる。prototypeモデルのuserデータのIDを拾うだけ。 %>
    <%# underfinded method 'id' for nil:NilClassはidの前の記述が中身が空。エラーページの下にcurrent_user入力する。 %>
  </div>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
       <div class="greeting">
         こんにちは、
         <%= link_to "#{current_user.name}さん", user_path(current_user.id), class: :greeting__link%>
         <%# パスがuser_pathで、rails routesを見ると、右にuser_showとある為、userコントローラーのshowアクションに移動。次にviwのuserに飛ぶ。 %>
          <%# ログインしているはcurrent_user のid 。 %>
          <%# パスは二つありどっちを使用しても良い。<%= link_to "マイページ", "/users/#{current_user.id}" %> 
          <%# では、"は文字列を表す為、current_user.idは変数として扱う為、"がいる。#は二つ目のパスの時必要。current_user_idは、<% if user_signed_in? %>
      </div>
      <% end %>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
      <%= render partial: 'prototype', collection: @prototypes %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.title%>
      </p>
      <%= link_to  @prototype.user.name, user_path(@prototype.user.id), class: :prototype__user %>
      <%# user_pathはrails routeのuserpath。(@prototype.user.id)@prototypeのuserのid。 %>

      <%# rails routesでidがついていた場合は、idは必須。 %>
      <%# @prototypeのルートは、index.html→renderで_prototypeの %>
      <%# <%= link_to image_tag(prototype.image, class: :card__img ), prototype_path(prototype.id)%>
      <%# 写真をクリックするとprototype_path(prototype.id)→controllerのfind(params[:id])に入る。 %>
      <%# → @prototypeに代入。showに飛んで、(@prototype.user.id)で@prototypeに代入。 %>


      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
     <% if user_signed_in? && current_user.id == @prototype.user_id %>

        <div class="prototype__manage">
          <%= link_to "編集する", edit_prototype_path(@prototype.id), class: :prototype__btn %>
          <%= link_to "削除する",  prototype_path(@prototype.id), data: { turbo_method: :delete } , class: :prototype__btn %>
        </div>
        <% end %>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">

        <%= image_tag @prototype.image, class: "prototype-image" if @prototype.image.attached? %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
        <% if user_signed_in? %>
           <%= form_with model: [@prototype, @comment], local: true do |f| %>
            <%# comtrollerの@prototype, @commentのインスタンスを使用。 [f]はブロック変数で下記の f fと同じにする必要がある。文字は何でも良い。 %>
            <%# @prototype, @commentが発動し、commentコントローラーに移動する。paramsに入れる。 %>
            <div class="field">
               <%= f.label :content, "コメント" %><br/>
               <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
               <%= f.submit "送信する", class: :form__btn  %>
            </div>
           <% end %>
           <% end %>

        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
          <% @comments.each do |comment| %>
          <%# コメントされた中のコメントを一つ取り出す。@commentsはproのcontrollのshow %>
          <%# コメントを空のまま押したが、エラーとなった。ターミナルのStarted POST→CommentsController#createに飛ぶ。@commentsを定義する。 %>
            <li class="comments">
             <%= comment.content %>
             <%# 上のブロック変数の|comment| の、テーブルのカラムのcontent %>
              <%= link_to comment.user.name , user_path(comment.user.id), class: :comment_user %>
              <%# commentのuseテーブルのname(これで名前が表示される。) pathはrailsroutesのshowアクションのパスを見る %>
              <%# commentは63行目の一つのコメント。user.idはアソシエーションで %>
              <%# コメントテーブルのIDを欄のuserid欄を連携し、userテーブルの番号のところに飛ぶ。 %>
            </li>
            <% end %>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
       <%= "#{@user.name}さんの情報" %>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= "#{@user.name}" %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= "#{@user.profile}" %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= "#{@user.occupation}" %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= "#{@user.position}" %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
         <%= "#{@user.name}さんのプロトタイプ" %>
      </h2>
      <div class="user__card">
      <%= render partial: 'prototypes/prototype', collection: @prototypes %>
      <%# 部分テンプレートをディレクトリをまたぐときは /を入れる。https://pikawaka.com/rails/partial_template %>
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
      </div>
    </div>
  </div>
</div>